apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-playzir
  labels:
    type: local
spec:
  storageClassName: storage-playzir
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-playzir"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-playzir
spec:
  storageClassName: storage-playzir
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi