apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vintagestory
  namespace: vintagestory
  labels:
    type: local
spec:
  storageClassName: storage-vintagestory
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-vintagestory"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vintagestory
  namespace: vintagestory
spec:
  storageClassName: storage-vintagestory
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi