apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minecraft-base
  labels:
    type: local
spec:
  storageClassName: storage-minecraft-base
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-minecraft-base"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minecraft-base
spec:
  storageClassName: storage-minecraft-base
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi