grafana:
  enabled: true
  defaultDashboardsEnabled: true
  persistence:
    enabled: true
    storageClassName: storage-kps
    existingClaim: pvc-kube-prometheus-stack

prometheusOperator:
  resources:
    requests:
      cpu: 600m
      memory: 600Mi
    limits:
      cpu: 1000m
      memory: 1000Mi
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 600m
        memory: 600Mi
      limits:
        cpu: 1000m
        memory: 1000Mi

# Allows prometheus to search metrics in different namespaces
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    additionalScrapeConfigs:
      - job_name: 'minecraft'
        static_configs:
          - targets: [ 'localhost:9940' ]
            labels:
              server_name: 'playzir'