apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-dashboard
  name: grafana-dashboard
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: minecraft
      nodePort: 32323
      port: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: grafana
  type: NodePort