apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kube-prometheus-stack
  labels:
    type: local
spec:
  storageClassName: storage-kps
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-kube-prometheus-stack"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kube-prometheus-stack
spec:
  storageClassName: storage-kps
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

