resources:
  requests:
    memory: 8Gi
    cpu: 1
  limits:
    memory: 24Gi
    cpu: 3

minecraftServer:
  version: LATEST
  type: "PAPER"
  paperDownloadUrl:
  difficulty: hard
  whitelist:
  ops:
  forcegameMode: true
  levelSeed:
  maxWorldSize: 50000
  gameMode: survival
  motd: "Welcome to Minecraft on Kubernetes"
  pvp: true
  serviceType: NodePort
  downloadWorldUrl:
  nodePort: 30000
  viewDistance: 15
  memory: 8Gi

  rcon:
    enabled: true
    nodePort: 30000
    serviceType: NodePort
    password: "globe"

extraEnv:
  ENABLE_ROLLING_LOGS: true
  OVERRIDE_SERVER_PROPERTIES: true
  FORCE_WORLD_COPY: false

persistence:
  dataDir:
    enabled: true
    Size: 20Gi