resources:
  requests:
    memory: 6Gi
    cpu: 1
  limits:
    memory: 24Gi
    cpu: 4

minecraftServer:
  version: "1.20.1"
  type: "FABRIC"
  fabricLauncherVersion: "1.0.3"
  fabricLoaderVersion: "0.16.10"
  difficulty: normal
  whitelist:
  ops: "Sentrance"
  forcegameMode: true
  levelSeed:
  maxWorldSize: 50000
  gameMode: survival
  motd: "Welcome to Minecraft on Kubernetes"
  pvp: true
  serviceType: ClusterIP
  servicePort: 25565
  viewDistance: 20
  memory: 16g

extraEnv:
  ENABLE_ROLLING_LOGS: true
  OVERRIDE_SERVER_PROPERTIES: true
  FORCE_WORLD_COPY: false
  MAX_TICK_TIME: -1
  ALLOW_FLIGHT: true

persistence:
  dataDir:
    enabled: true
    existingClaim: pvc-playzir

podSecurityContext:
  runAsGroup: 3000
  fsGroup: 3000