resources:
  requests:
    memory: 6Gi
    cpu: 1
  limits:
    memory: 24Gi
    cpu: 2

minecraftServer:
  version: LATEST
  type: "AUTO_CURSEFORGE"
  difficulty: hard
  whitelist:
  ops:
  forcegameMode: true
  levelSeed:
  maxWorldSize: 50000
  gameMode: survival
  motd: "Welcome to Minecraft on Kubernetes"
  pvp: true
  serviceType: ClusterIP
  servicePort: 25565
  viewDistance: 20
  memory: 8g
  autoCurseForge:
    apiKey:
      key: ""
    pageUrl: "https://mediafilez.forgecdn.net/files/6475/395/Prominence_II_RPG_Hasturian_Era_Server_Pack_v3.1.10.zip"


  rcon:
    enabled: true
    password: "globe"

extraEnv:
  ENABLE_ROLLING_LOGS: true
  OVERRIDE_SERVER_PROPERTIES: true
  FORCE_WORLD_COPY: false

persistence:
  dataDir:
    enabled: true
    existingClaim: pvc-playzir

podSecurityContext:
  runAsGroup: 3000
  fsGroup: 3000